- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Create CI directory
  file:
    path: /opt/ci
    state: directory

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: /opt/ci/docker-compose.yaml
    mode: '0644'

- name: Copy NGINX config
  template:
    src: nginx.conf.j2
    dest: /opt/ci/nginx.conf
    mode: '0644'

- name: Start containers
  shell: docker-compose up -d
  args:
    chdir: /opt/ci

- name: Create JCasC config directory
  file:
    path: /opt/ci/jenkins/casc_configs
    state: directory
    recurse: true

- name: Copy Jenkins JCasC config
  template:
    src: jenkins.yaml.j2
    dest: /opt/ci/jenkins/casc_configs/jenkins.yaml
    mode: '0644'
  notify: Restart CI stack

