name: "Configure Infra"

on:
  workflow_dispatch:

jobs:
  configure-infra:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2  # Change if needed

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/k4scloud-key.pem
          chmod 600 ~/.ssh/k4scloud-key.pem

      - name: Disable Ansible Host Key Checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      - name: Install Ansible and AWS Collections
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Ansible Playbook to Configure Infra
        working-directory: infra/ansible
        run: ansible-playbook playbooks/clean-infra.yaml
